# Generated by Django 5.1.6 on 2025-02-27 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='제목')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phonenumber', models.CharField(max_length=20, null=True, verbose_name='전화번호')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'db_table': 'announcement',
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=50, verbose_name='고객 별명')),
                ('name', models.CharField(max_length=50, verbose_name='고객이름')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='고객 전화번호')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('ages', models.CharField(max_length=20, verbose_name='연령대')),
                ('isBadClient', models.BooleanField(default=False, verbose_name='불량 고객 유무')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='특이사항')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객 목록',
                'db_table': 'clients2',
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='관리자 여부')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
    ]
