# Generated by Django 5.1.6 on 2025-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='고객이름'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nickName',
            field=models.CharField(max_length=100, verbose_name='고객 별명'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=1000, verbose_name='고객 전화번호'),
        ),
    ]
