# Generated by Django 5.1.6 on 2025-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0002_alter_client_name_alter_client_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickName',
            field=models.CharField(max_length=100, unique=True, verbose_name='고객 별명'),
        ),
    ]
