# Generated by Django 5.1.6 on 2025-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0003_alter_client_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_license_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='사업자등록증'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='조회가능횟수'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='매장명'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='이용가능횟수'),
        ),
    ]
