# Generated by Django 5.1.6 on 2025-03-04 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0004_user_business_license_image_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usage_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='이용 가능 마감일'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='이용 가능 시작일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
    ]
