# Generated by Django 5.1.6 on 2025-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0005_user_usage_end_date_user_usage_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='사용기간'),
        ),
    ]
