# Generated by Django 5.1.6 on 2025-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0008_remove_announcement_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registeredBy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='등록한 사용자 ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='등록한 사용자 매장명'),
        ),
    ]
