# Generated by Django 5.1.6 on 2025-04-07 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0009_client_registeredby_client_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='소재지')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('isDefenderActive', models.BooleanField(default=True, verbose_name='앱 사용 여부')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='defender.user', verbose_name='소유자 ID')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장 목록',
                'db_table': 'stores',
                'ordering': ['-createDate'],
            },
        ),
    ]
