# Generated by Django 5.1.6 on 2025-04-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0010_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='storeName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='매장명'),
        ),
    ]
