# Generated by Django 5.1.6 on 2025-04-07 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defender', '0011_store_storename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='ownerId',
            field=models.ForeignKey(db_column='ownerId', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='defender.user', verbose_name='소유자 ID'),
        ),
    ]
